app/routes.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import current_user, login_user, logout_user, login_required
from decimal import Decimal
from app.forms import LoginForm, RegistrationForm, MoneyForm, TransferForm, AcceptForm, DeclineForm, CancelForm
from app.models import User, Account, Transaction, Session, AccountType, TransactionStatus, TransactionType
from app.extensions import db
from urllib.parse import urlsplit
import sqlalchemy as sa 
from flask_login import login_required
from datetime import datetime, timezone
import logging
import requests

bp = Blueprint("main", __name__)

logging.basicConfig(level=logging.DEBUG)

@bp.route('/')
def index():
    return render_template('base.html')

@bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = db.session.scalar(
            sa.Select(User).where(User.username == form.username.data)
        )
        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password')
            return redirect(url_for('main.login'))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')
        ip = request.remote_addr
        session = Session(ip=ip, user=current_user, )
        if not next_page or urlsplit(next_page).netloc != '':
            next_page = url_for('main.home')
        return redirect(next_page)

    return render_template('login.html', title='Sign In', form=form)

@bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        accounts = [
                    Account(user=user, balance=Decimal('292.12'), account_type=AccountType.CHECKING),
                    Account(user=user, balance=Decimal('914.34'), account_type=AccountType.SAVINGS)
                    ]
        user.accounts = accounts
        db.session.add(user)
        db.session.commit()
        flash('Congratulations, you are now a registered user!')
        login_user(user)
        return redirect(url_for('main.home'))
    return render_template('register.html', title='Register', form=form)

@bp.route('/contact_us')
def contact_us():
    return render_template('contact_us.html')

@bp.route('/home')
@login_required
def home():
    return render_template('home.html', title='home', user=current_user, accounts=current_user.accounts, AccountType=AccountType)

@bp.route('/add_money', methods=['GET', 'POST'])
@login_required
def add_money():
    form = MoneyForm()
    if form.validate_on_submit():
        print(form.account_type.data)
        user_account = db.session.scalar(
            sa.select(Account)
            .where(Account.user == current_user,
                    Account.account_type == AccountType(form.account_type.data)
            )
        )
        if not user_account:
            flash('Banking Account not found')
            return redirect(url_for('main.add_money'))
        user_account.balance += form.amount.data
        db.session.commit()
        flash(f'Successfully added {form.amount.data} to your {form.account_type.data} account')
    return render_template('add_money.html', form=form)

@bp.route('/transfer', methods=['GET', 'POST'])
@login_required
def transfer():
    form = TransferForm()
    action = request.form.get('action')

    if action in ["accept", "decline", "cancel"]:
        transaction_id = request.form.get('transaction_id')

        if not transaction_id:
            flash("Missing transaction id")

        transaction = db.session.get(Transaction, int(transaction_id))

        if action == 'accept':
            if transaction.complete_transaction():
                flash('Transaction successfully completed')
            else:
                flash('Failed to complete transaction')

        if action == 'decline':
            transaction.cancel_transaction()
            flash('Transaction successfully declined')

        if action == 'cancel':
            transaction.cancel_transaction()
            flash('Transaction succesfully cancelled')

    if form.validate_on_submit():
        logging.debug("testingu1298123")
        if form.choice_field.data == "between_users":
            logging.debug('between_users')
            to_user = db.session.scalar(
                sa.select(User)
                .where(User.username == form.user_field.data)
            )
            if not to_user:
                flash('User not found')
                return redirect(url_for('main.transfer'))
            
            sending_account = db.session.scalar(
                sa.select(Account)
                .where(Account.user == current_user,
                    Account.account_type == AccountType.CHECKING
                )
            )

            receiving_account = db.session.scalar(
                sa.select(Account)
                .where(Account.user == to_user,
                    Account.account_type == AccountType.CHECKING
                )
            )

            transaction = Transaction(from_account=sending_account, 
                                      to_account=receiving_account, 
                                      transaction_type=TransactionType(form.request_type.data),
                                      status = TransactionStatus.PENDING,
                                      amount=form.amount.data)
            db.session.add(transaction)
            db.session.commit()

        if form.choice_field.data == "between_accounts":
            logging.debug('between_accounts')
            sending_account = db.session.scalar(
                sa.select(Account)
                .where(Account.user == current_user,
                    Account.account_type == AccountType(form.account1.data)
                )
            )
            logging.debug(sending_account)
            receiving_account = db.session.scalar(
                sa.select(Account)
                .where(Account.user == current_user,
                    Account.account_type == AccountType(form.account2.data)
                )
            )
            logging.debug(receiving_account)
            transaction = Transaction(from_account=sending_account, 
                                      to_account=receiving_account, 
                                      transaction_type=TransactionType.SEND,
                                      status = TransactionStatus.PENDING, 
                                      amount=form.amount.data)
            db.session.add(transaction)
            db.session.commit()

            if transaction.complete_transaction():
                flash(f'Successfully transferred ${transaction.amount}' )
            else:
                flash('Insufficient balance')
                
            return redirect(url_for('main.transfer'))

    return render_template('transfer.html', form=form, user=current_user, TransactionType=TransactionType, AccountType=AccountType)
    


@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

app/templates/add_money.html
{% extends "base.html" %}

{% block content %}
<form method="post" novalidate>
    {{ form.hidden_tag() }}
    <p>
        {{ form.account_type.label}}
        {{ form.account_type() }}
        {% for error in form.account_type.errors %}
        <span>{{ error }}</span>
        {% endfor %}
    </p>
    <p>
        {{ form.amount.label }}<br>
        {{ form.amount(size=32) }}
        {% for error in form.amount.errors %}
        <span>{{ error }}</span>
        {% endfor %}
    </p>
    <p>{{ form.submit() }}</p>
</form>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Welcome to hooper banking</title>
</head>

<body>
    <div>
        <img src="{{ url_for('static', filename='images/logo.png')}}">
        <a href="{{ url_for('main.home')}}">Home</a>
        <a href="{{ url_for('main.login')}}">Log In</a>
        <a href="{{ url_for('main.register')}}">Register</a>
        <a href="{{ url_for('main.contact_us')}}">Contact us</a>
        <a href="{{ url_for('main.logout')}}">Logout</a>
    </div>
    <hr>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <u1>
        {% for message in messages %}
        <l1>{{ message }}</l1>
        {% endfor %}
    </u1>
    {% endif %}
    {% endwith %}
    {% block content %}{% endblock %}
</body>

</html>

app/templates/contact_us.html
{% extends "base.html" %}

{% block content %}

{% endblock %}

app/templates/home.html
{% extends "base.html" %}

{% block content %}
<h1>Hello, {{ user.username }}!</h1>
{% for account in accounts %}
{% if account.account_type == AccountType.CHECKING %}
<div>
    <h2>
        Checking Account - ${{ account.balance }}
    </h2>
</div>
{% elif account.account_type == AccountType.SAVINGS %}
<div>
    <h2>
        Savings Account - ${{ account.balance }}
    </h2>
</div>
{% endif %}
{% endfor %}
<form action="{{ url_for('main.add_money') }}" method="get">
    <button type="submit">Add some money</button>
</form>
<br>
<form action="{{ url_for('main.transfer') }}" method="get">
    <button type="submit">Transfer to somebody...</button>
</form>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block content %}
<h1>Login</h1>
<form method="post" novalidate>
    {{ form.hidden_tag() }}
    <p>
        {{ form.username.label }}<br>
        {{ form.username(size=32) }}
        {% for error in form.username.errors %}
        <span>{{ error }}</span>
        {% endfor %}
    </p>
    <p>
        {{ form.password.label }}<br>
        {{ form.password(size=32) }}
        {% for error in form.password.errors %}
        <span>{{error }}</span>
        {% endfor %}
    </p>
    <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
    <p>{{ form.submit() }}</p>
</form>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}

{% block content %}
<h1>Sign Up</h1>

<form method="post" novalidate>
    {{ form.hidden_tag() }}
    <p>
        {{ form.username.label }}<br>
        {{ form.username(size=32) }}
        {% for error in form.username.errors %}
        <span>{{ error }}</span>
        {% endfor %}
    </p>
    <p>
        {{ form.email.label }} <br>
        {{ form.email(size=32) }}
        {% for error in form.email.errors %}
        <span> {{ error }}</span>
        {% endfor %}
    </p>
    <p>

    </p>
    <p>
        {{ form.password.label }}<br>
        {{ form.password(size=32) }}
        {% for error in form.password.errors %}
        <span>{{error }}</span>
        {% endfor %}
    </p>

    <p>
        {{ form.password2.label }}<br>
        {{ form.password2(size=32) }}
        {% for error in form.password2.errors %}
        <span>{{error }}</span>
        {% endfor %}


    </p>
    <p>{{ form.submit() }}</p>
</form>
{% endblock %}

app/templates/transfer.html
{% extends "base.html" %}

{% block content %}
<h1>Transfer</h1>

<form method="post" novalidate>
    {{ form.hidden_tag() }}

    <p>
        {{ form.choice_field.label }}<br>
        {{ form.choice_field(id="choice_field") }}
        {% for error in form.choice_field.errors %}
        <span>{{error }}</span>
        {% endfor %}
    </p>

    <!-- USER FIELDS -->
    <div id="user_field" style="display:none;">
        <p>
            {{ form.request_type.label }}<br>
            {{ form.request_type() }}
            {% for error in form.request_type.errors %}
            <span>{{error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.user_field.label }}<br>
            {{ form.user_field() }}
            {% for error in form.user_field.errors %}
            <span>{{error }}</span>
            {% endfor %}
        </p>
    </div>

    <!-- ACCOUNT FIELDS -->
    <div id="account_fields" style="display:none;">
        <p>
            {{ form.account1.label }}<br>
            {{ form.account1() }}
            {% for error in form.account1.errors %}
            <span>{{error }}</span>
            {% endfor %}
        </p>

        <p>
            {{ form.account2.label }}<br>
            {{ form.account2() }}
            {% for error in form.account2.errors %}
            <span>{{error }}</span>
            {% endfor %}
        </p>
    </div>
    <div id="amount_field" style="display:none;">
        <p>
            {{ form.amount.label }}<br>
            {{ form.amount() }}
            {% for error in form.amount.errors %}
            <span>{{error }}</span>
            {% endfor %}
        </p>
    </div>

    <p>{{ form.submit() }}</p>
</form>

<h1>Incoming Transactions</h1>

<div id="incoming-transactions">

    {% for transaction in user.get_incoming_transactions() %}

    <table class="transaction-table">
        <tr>
            <th>From</th>
            <th>Type</th>
            <th>Amount</th>
            <th>Accept</th>
            <th>Decline</th>
        </tr>

        <tr>
            <td>{{ transaction.from_account.user.username }}</td>
            <td>{{ transaction.transaction_type.value }}</td>
            <td>{{ transaction.amount }}</td>

            <td>
                <form method="POST" novalidate>
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">

                    <input type="hidden" name="transaction_id" value="{{ transaction.id }}">

                    <button type="submit" name="action" value="accept">
                        Accept
                    </button>
                </form>
            </td>
            <td>
                <form method="POST" novalidate>
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">

                    <input type="hidden" name="transaction_id" value="{{ transaction.id }}">


                    <button type="submit" name="action" value="decline">
                        Decline
                    </button>
                </form>
            </td>
        </tr>
    </table>

    {% endfor %}

</div>

<h1>Outgoing Transactions</h1>

<div id="outgoing-transactions">

    {% for transaction in user.get_outgoing_transactions() %}

    <table class="transaction-table">
        <tr>
            <th>To</th>
            <th>Type</th>
            <th>Amount</th>
            <th>Cancel</th>
        </tr>

        <tr>
            <td>{{ transaction.to_account.user.username }}</td>
            <td>{{ transaction.transaction_type.value.capitalize() }}</td>
            <td>{{ transaction.amount }}</td>

            <td>
                <form method="POST" novalidate>
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">

                    <input type="hidden" name="transaction_id" value="{{ transaction.id }}">
                    <button type="submit" name="action" value="cancel">
                        Cancel
                    </button>
                </form>
            </td>
        </tr>
    </table>

    {% endfor %}

</div>


<h1>Completed Transactions</h1>
<!-- Include from in incoming transactions, to in outgoing transactions, and both in internal ones
     Make each transaction an individual table -->
<div id="completed_transactions">
    {% for transaction in user.get_completed_transactions() %}

    <table class="transaction-table">
        <tr>
            <!--{% if transaction.is_internal() %}
            <th>To</th>
            <th>From</th>
            {% elif transaction.transaction_type == TransactionType.SEND%}
            <th>To</th>
            {% else %}
            <th>From</th>
            {% endif %}-->
            <th>To</th>
            <th>From</th>
            <th>Type</th>
            <th>Amount</th>
            <th>Status</th>
        </tr>
        <tr>
            {% if transaction.is_internal() %}
            <td>{{transaction.from_account.account_type.value.capitalize()}}</td>
            <td>{{transaction.to_account.account_type.value.capitalize()}}</td>
            {% else %}
            <td>{{transaction.to_account.user.username}}</td>
            <td>{{transaction.from_account.user.username}}</td>
            {% endif %}
            <td>{{ transaction.transaction_type.value.capitalize() }}</td>
            <td>{{ transaction.amount }}</td>
            <td>{{ transaction.status.value}}</td>
        </tr>
        {% endfor %}
</div>

<h1>Cancelled Transactions</h1>
<!-- Include from in incoming transactions, to in outgoing transactions, and both in internal ones
     Make each transaction an individual table -->
<div id="cancelled_transactions">
    {% for transaction in user.get_cancelled_transactions() %}

    <table class="transaction-table">
        <tr>
            <!--{% if transaction.is_internal() %}
            <th>To</th>
            <th>From</th>
            {% elif transaction.transaction_type == TransactionType.SEND%}
            <th>To</th>
            {% else %}
            <th>From</th>
            {% endif %}-->
            <th>To</th>
            <th>From</th>
            <th>Type</th>
            <th>Amount</th>
            <th>Status</th>
        </tr>
        <tr>
            {% if transaction.is_internal() %}
            <td>{{transaction.from_account.account_type.value.capitalize()}}</td>
            <td>{{transaction.to_account.account_type.value.capitalize()}}</td>
            {% else %}
            <td>{{transaction.to_account.user.username}}</td>
            <td>{{transaction.from_account.user.username}}</td>
            {% endif %}
            <td>{{ transaction.transaction_type.value.capitalize() }}</td>
            <td>{{ transaction.amount }}</td>
            <td>{{ transaction.status.value}}</td>
        </tr>
        {% endfor %}
</div>



<script>
    document.addEventListener("DOMContentLoaded", function () {

        const choice = document.getElementById("choice_field");
        const userField = document.getElementById("user_field");
        const accountFields = document.getElementById("account_fields");
        const amountField = document.getElementById("amount_field");

        function toggleFields() {
            if (choice.value === "between_users") {
                userField.style.display = "block";
                amountField.style.display = "block";
                accountFields.style.display = "none";
            }
            else if (choice.value === "between_accounts") {
                accountFields.style.display = "block";
                amountField.style.display = "block";
                userField.style.display = "none";
            }
            else {
                userField.style.display = "none";
                accountFields.style.display = "none";
                amountField.style.display = "none";
            }
        }

        choice.addEventListener("change", toggleFields);

        // Initial state
        toggleFields();

    });
</script>


{% endblock %}